### ISSUE TITLE
Compile error on Fedora 17

### ISSUE THREAD

**Issue by neonfuzz** [myszha/qt-ponies#4]
I receive the following error when trying to compile on Fedora 17, Gnome 3.4, 64-bit architecture:

<code>[addie@CremaCatalana qt-ponies]$ make
g++ -m64 -Wl,-O1 -Wl,-rpath,/home/addie/.QtSDK/Desktop/Qt/4.8.1/gcc/lib -o qt-ponies bin/main.o bin/pony.o bin/behavior.o bin/effect.o bin/speak.o bin/configwindow.o bin/csv_parser.o bin/interaction.o bin/debugwindow.o bin/moc_pony.o bin/moc_speak.o bin/moc_configwindow.o bin/moc_debugwindow.o bin/qrc_qt-ponies.o    -L/home/addie/.QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/addie/.QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
/usr/bin/ld: warning: libpng12.so.0, needed by /home/addie/.QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: bin/pony.o: undefined reference to symbol 'XInternAtom'
/usr/bin/ld: note: 'XInternAtom' is defined in DSO /lib64/libX11.so.6 so try adding it to the linker command line
/lib64/libX11.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: **\* [qt-ponies] Error 1
</code>

Still being somewhat of a newb when it comes to compiling from source, I'm stuck.
I've tried running the system qmake (qmake-qt4) as well as the proprietary version from qt.nokia.com; both receive the same error.  I'm fairly certain I need to add -lX11 to a line in the makefile (from Internet search), but I wouldn't know where that should appear.  I have the libX11, libX11-common and libX11-devel packages all installed.

**Comment by myszha** [comment]
It should be fixed. You may also want to install libpng12 from what I can see.
